version: '2'
services:

  reactive-app01:
    image: an3ll/kotlin-reactive-app
    ports:
      - 8082:8080
    labels:
      io.rancher.scheduler.affinity:host_label: "host=host2"

  reactive-app02:
    image: an3ll/kotlin-reactive-app
    ports:
      - 8081:8080
    labels:
      io.rancher.scheduler.affinity:host_label: "host=host1"